version: "3.8"

services:
  db:
    image: postgres:15
    container_name: tasks_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: tasks_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./api
      dockerfile: ../Dockerfile.api
    container_name: tasks_api
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    container_name: tasks_client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  pgdata:
